# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - name: echo
      run: echo helloworld
        
  my_job2:
    name: seconds job
    runs-on: ubuntu-18.04
    steps:
    - name: echo2
      run: echo helloworld
  
  my_job3:
    name: 3rd job
    needs: [my_job,my_job2]
    runs-on: ubuntu-18.04
    steps:
    - name: echo2
      run: echo helloworld
          
  
